### ISSUE TITLE
Avoid selecting text inside tiles

### ISSUE THREAD

**Issue by codealchemist** [codealchemist/minesweeper#1]

**Comment by fjn2** [comment]
I think we need to add:

`user-select: none;`

In the following element:

https://github.com/codealchemist/minesweeper/blob/67bcdf282b17e1feb98f81d73282f5b3e656a4a9/src/elements.js#L65

**Comment by codealchemist** [comment]
> I think we need to add:
> 
> `user-select: none;`
> 
> In the following element:
> 
> https://github.com/codealchemist/minesweeper/blob/67bcdf282b17e1feb98f81d73282f5b3e656a4a9/src/elements.js#L65

Yeah, that's perfect!
Thanks @fjn2 !

Fixed on d7d0868.
